name: CommandManager
version: ${project.version}
main: me.charashenko.commandmanager.CommandManager
api-version: 1.16
description: Minecraft plugin, CommandManager build for Paper 1.16.4
commands:
  perm:
    description: Base command from which all subcommands extend
    usage: If you need help, try /perm help
